site_name: Trainees-FiSi
repo_name: Trainees-FiSi
repo_url: https://github.com/skyface753/Trainees-FiSi
edit_uri: 'tree/main/docs/'
site_url: https://skyface753.github.io/Trainees-FiSi/
theme:
  name: material
  features:
    - content.code.copy
    # Disabled, because it prevents the js for the quiz from working
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
    # - navigation.footer
    # - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.instant.progress
  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    tag:
      service: material/apps
extra_css:
  - assets/css/neoteroi-mkdocs.css
markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - neoteroi.timeline
  - toc:
      permalink: true

extra:
  tags:
    Service: service
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enabled: !ENV [ENABLED_GIT_PLUGINS, True]
  # - git-committers:
  #     repository: squidfunk/mkdocs-material
  #     branch: main
  - git-authors:
      enabled: !ENV [ENABLED_GIT_PLUGINS, True]
  - mkdocs_quiz
  - open-in-new-tab # Open all external links in a new tab
  - tags
  - thumbnails:
      style: margin-top:5px;margin-bottom:5px;margin-right:25px
  # Last plugin
  - print-site
# Nav gets generated by `.pages` files in the folders
# Add new folders to the `docs/.pages` file
